In [1]:
# Create a null vector of size 10 but the fifth value which is 1.

import numpy as np

a = np.zeros(10)

a[4] = 1

print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# Create a Vector with values ranging from 10 to 49.

vector = np.arange(10,50)

print(vector)


  

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# Create a 3x3 matrix with values ranging from 0 to 8

a = np.arange(0,9)

b = a.reshape(3,3)

print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# Find indices of non-zero elements from [1,2,0,0,4,0]

a = np.array([1,2,0,0,4,0])

indices = np.nonzero(a)

print(indices)

(array([0, 1, 4]),)


In [9]:
# Create a 10x10 array with random values and find the minimum and maximum values

a = np.random.random((10,10))

mix_val = np.max(a)
min_val = np.min(a)

print(a)
print("Maximum value: ",mix_val)
print("Minimun value: ",min_val)


[[0.26237864 0.61363298 0.48978887 0.39075591 0.18725062 0.16934491
  0.81959358 0.13261413 0.17810044 0.08876255]
 [0.9137137  0.2787752  0.53305612 0.56894501 0.98555941 0.89260273
  0.17244226 0.20828364 0.38272683 0.60384292]
 [0.54464858 0.91145647 0.18172451 0.24446285 0.47914909 0.90941829
  0.56127082 0.94998984 0.30564119 0.32628097]
 [0.55464241 0.6855574  0.80176998 0.96905288 0.4233535  0.8129491
  0.10418443 0.52002496 0.64359932 0.01842316]
 [0.85243606 0.30628754 0.28147804 0.38179698 0.46643475 0.84898245
  0.90892771 0.68463279 0.44653452 0.44575638]
 [0.20022111 0.68448358 0.25114716 0.87078834 0.33028042 0.72526396
  0.18856158 0.64255077 0.90543587 0.03686285]
 [0.45815631 0.94910558 0.47679419 0.13843373 0.76598539 0.88465745
  0.7976589  0.30647993 0.98157929 0.34945271]
 [0.41433491 0.52088764 0.94869775 0.3290199  0.72428416 0.6057811
  0.68357538 0.42474725 0.23459426 0.38344532]
 [0.76891555 0.67215814 0.0536117  0.23908853 0.33454529 0.74860776
  0.94161196 0

In [10]:
# Create a random vector of size 30 and find the mean value.

a = np.random.random(30)

mean_val = np.mean(a)

print("Mean Value: ",mean_val)

Mean Value:  0.47359438279653754
